(miniproject) C:\Users\SATYA\miniproject>python attack.py --dataset BrainTumor --attack FGSM
Using TensorFlow backend.
FGSM attack on BrainTumor classification model.

 load data...
Loading Train data: 100%|████████████████████████████████████████████████████████████████| 4/4 [00:47<00:00, 11.76s/it]
Loading Train data: 100%|████████████████████████████████████████████████████████████████| 4/4 [00:37<00:00,  9.29s/it]
data loaded.

 load model...
Traceback (most recent call last):
  File "attack.py", line 274, in <module>
    attack_obj = AdvAttack(FLAGS.dataset, FLAGS.attack)
  File "attack.py", line 46, in __init__
    self.execute_attack()
  File "attack.py", line 255, in execute_attack
    self._load_dataset_model()
  File "attack.py", line 95, in _load_dataset_model
    self.model = load_model(f'saved_models/{model_file_name}')
  File "C:\Users\SATYA\.conda\envs\miniproject\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "C:\Users\SATYA\.conda\envs\miniproject\lib\site-packages\keras\engine\saving.py", line 550, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "C:\Users\SATYA\.conda\envs\miniproject\lib\site-packages\keras\engine\saving.py", line 243, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\SATYA\.conda\envs\miniproject\lib\site-packages\keras\engine\saving.py", line 593, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\SATYA\.conda\envs\miniproject\lib\site-packages\keras\layers\__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "C:\Users\SATYA\.conda\envs\miniproject\lib\site-packages\keras\utils\generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\SATYA\.conda\envs\miniproject\lib\site-packages\keras\engine\sequential.py", line 301, in from_config
    custom_objects=custom_objects)
  File "C:\Users\SATYA\.conda\envs\miniproject\lib\site-packages\keras\layers\__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "C:\Users\SATYA\.conda\envs\miniproject\lib\site-packages\keras\utils\generic_utils.py", line 149, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "C:\Users\SATYA\.conda\envs\miniproject\lib\site-packages\keras\engine\base_layer.py", line 1103, in from_config
    return cls(**config)
  File "C:\Users\SATYA\.conda\envs\miniproject\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'ragged'